AlmacenBundle\Entity\Categoria:
    type: entity
    table: categorias
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    oneToMany:
      producto:
        targetEntity: Producto
        mappedBy: categoria
        cascade: ["persist"]
    lifecycleCallbacks: {  }
