AlmacenBundle\Entity\Etiqueta:
    type: entity
    table: etiquetas
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        descripcion:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    oneToMany:
      productoEtiqueta:
        targetEntity: ProductoEtiqueta
        mappedBy: etiqueta
        cascade: ["persist"]
    lifecycleCallbacks: {  }
