AlmacenBundle\Entity\Usuario:
    type: entity
    table: usuarios
    indexes:
        fk_usuarios_grupos:
            columns:
                - grupo_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        apellidos:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        pass:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        role:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        img:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        grupo:
            targetEntity: Grupo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: usuario
            joinColumns:
                grupo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
